{
  "artifacts": [],
  "command": "rollouts_and_policy",
  "experiment": {
    "base_dir": "/home/katy/imitation/src/imitation/scripts/config",
    "dependencies": [
      "imitation==0.2.0",
      "numpy==1.21.0",
      "sacred==0.8.2"
    ],
    "mainfile": "expert_demos.py",
    "name": "expert_demos",
    "repositories": [
      {
        "commit": "740f4eefd6eb6aa04e5fee68151336dc1861615d",
        "dirty": true,
        "url": "http://github.com/HumanCompatibleAI/imitation"
      }
    ],
    "sources": [
      [
        "expert_demos.py",
        "_sources/expert_demos_63dd799090248e4e8fd120eed104e7b3.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/katy/miniconda3/envs/HumanCompatibleAI/lib/python3.7/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"/home/katy/imitation/src/imitation/scripts/expert_demos.py\", line 136, in rollouts_and_policy\n    post_wrappers=[lambda env, idx: wrappers.RolloutInfoWrapper(env)],\n",
    "  File \"/home/katy/imitation/src/imitation/util/util.py\", line 109, in make_vec_env\n    return SubprocVecEnv(env_fns, start_method=\"forkserver\")\n",
    "  File \"/home/katy/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py\", line 106, in __init__\n    observation_space, action_space = self.remotes[0].recv()\n",
    "  File \"/home/katy/miniconda3/envs/HumanCompatibleAI/lib/python3.7/multiprocessing/connection.py\", line 250, in recv\n    buf = self._recv_bytes()\n",
    "  File \"/home/katy/miniconda3/envs/HumanCompatibleAI/lib/python3.7/multiprocessing/connection.py\", line 407, in _recv_bytes\n    buf = self._recv(4)\n",
    "  File \"/home/katy/miniconda3/envs/HumanCompatibleAI/lib/python3.7/multiprocessing/connection.py\", line 379, in _recv\n    chunk = read(handle, remaining)\n",
    "ConnectionResetError: [Errno 104] Connection reset by peer\n"
  ],
  "heartbeat": "2021-08-14T16:57:08.178911",
  "host": {
    "ENV": {},
    "cpu": "AMD Ryzen 5 3600 6-Core Processor",
    "gpus": {
      "driver_version": "470.57.02",
      "gpus": [
        {
          "model": "NVIDIA GeForce GTX 1070",
          "persistence_mode": false,
          "total_memory": 8116
        }
      ]
    },
    "hostname": "katy-desktop",
    "os": [
      "Linux",
      "Linux-5.4.0-80-generic-x86_64-with-debian-buster-sid"
    ],
    "python_version": "3.7.10"
  },
  "meta": {
    "command": "rollouts_and_policy",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2021-08-14T16:57:04.706300",
  "status": "FAILED",
  "stop_time": "2021-08-14T16:57:08.180194"
}